# TODO: add windows and macOs support
name: Build and Test
on:
  push:
    branches:
      - '**'  # This matches all branches
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]
        compiler:
          - {
              cc: "gcc",
              cxx: "g++"
            }
          - {
              cc: "clang",
              cxx: "clang++"
            }

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev
        # Add any other dependencies your project needs

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_C_COMPILER=${{matrix.compiler.cc}} \
              -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} --output-on-failure
